# Initial Replicas
replicaCount: 1
# Docker Settings.
image:
    repository: ghcr.io/the-bob/fast-api
    pullPolicy: Always
    tag: latest_main
# Auto-Scalling Settings via HPA
autoscaling:
    enabled: true
    targetCPUUtilizationPercentage: 90
    targetMemoryUtilizationPercentage: 90
    maxReplicas: 5
    minReplicas: 1
# Pod Resources
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi
# Ingress
ingress:
    enabled: true
    hosts:
        - host: api.dev.opeeplresearch.com
          paths:
            - path: /
              pathType: Prefix
              port:
                number: 80
        - host: api.dev.opeeplresearch.com
          paths:
            - path: /*
              pathType: Prefix
              port:
                number: 80
    annotations:
      external-dns.alpha.kubernetes.io/hostname: api.dev.opeeplresearch.com
      external-dns.alpha.kubernetes.io/ttl: "60"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/ingress.allow-http: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.org/redirect-to-https: "true"

# Config Map
# config:
#     values:
#       DB_NAME: apidb
#       DB_HOST: apidb.default.svc.cluster.local
#       DB_PORT: 3306
