server:
  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts: ["argo.localhost"]


  # additionalApplications:
  #   - name: api
  #     namespace: argocd
  #     finalizers:
  #     - resources-finalizer.argocd.argoproj.io
 